/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorBatalla;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Lucas
 */
public class DespliegueDados extends javax.swing.JPanel  {
    
    Object boton;
    ControladorBatalla controlador;

    /**
     * Creates new form DespliegueDados
     */
    public DespliegueDados(ControladorBatalla cb) {
        initComponents();
        this.setSize(399, 401);
        this.controlador = cb;
    }
    
    public void paintComponent(Graphics g){
        Dimension dimensiones = getSize();
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/Imagenes/despliegue.png"));
        g.drawImage(imagenFondo.getImage(), 0, 0, dimensiones.width, dimensiones.height, null);
        setOpaque(false);
        super.paintComponent(g);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        despliegue1 = new javax.swing.JButton();
        despliegue2 = new javax.swing.JButton();
        despliegue3 = new javax.swing.JButton();
        despliegue6 = new javax.swing.JButton();
        despliegue5 = new javax.swing.JButton();
        despliegue4 = new javax.swing.JButton();
        despliegue9 = new javax.swing.JButton();
        despliegue8 = new javax.swing.JButton();
        despliegue11 = new javax.swing.JButton();
        despliegue7 = new javax.swing.JButton();
        despliegue10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();

        despliegue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue1ActionPerformed(evt);
            }
        });

        despliegue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue2ActionPerformed(evt);
            }
        });

        despliegue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue3ActionPerformed(evt);
            }
        });

        despliegue6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue6ActionPerformed(evt);
            }
        });

        despliegue5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue5ActionPerformed(evt);
            }
        });

        despliegue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue4ActionPerformed(evt);
            }
        });

        despliegue9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue9ActionPerformed(evt);
            }
        });

        despliegue8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue8ActionPerformed(evt);
            }
        });

        despliegue11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue11ActionPerformed(evt);
            }
        });

        despliegue7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue7ActionPerformed(evt);
            }
        });

        despliegue10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despliegue10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Elija el despliegue deseado.");

        cerrar.setText("Ver tablero.");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(despliegue7)
                            .addComponent(despliegue10)
                            .addComponent(despliegue4)
                            .addComponent(despliegue1))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(despliegue11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(cerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(despliegue2)
                                    .addComponent(despliegue5)
                                    .addComponent(despliegue8))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(despliegue9)
                                    .addComponent(despliegue6)
                                    .addComponent(despliegue3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despliegue1)
                    .addComponent(despliegue2)
                    .addComponent(despliegue3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(despliegue4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despliegue5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despliegue6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(despliegue7)
                            .addComponent(despliegue9))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(despliegue10)
                            .addComponent(despliegue11)
                            .addComponent(cerrar)))
                    .addComponent(despliegue8))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void despliegue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue1ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(1);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
        
    }//GEN-LAST:event_despliegue1ActionPerformed

    private void despliegue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue2ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(2);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue2ActionPerformed

    private void despliegue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue3ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(3);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue3ActionPerformed

    private void despliegue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue4ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(4);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue4ActionPerformed

    private void despliegue5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue5ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(5);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue5ActionPerformed

    private void despliegue6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue6ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(6);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue6ActionPerformed

    private void despliegue7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue7ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(7);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue7ActionPerformed

    private void despliegue8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue8ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(8);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue8ActionPerformed

    private void despliegue9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue9ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(9);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue9ActionPerformed

    private void despliegue10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue10ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(10);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue10ActionPerformed

    private void despliegue11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despliegue11ActionPerformed
        // TODO add your handling code here:
        this.controlador.setBoton(11);
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_despliegue11ActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false);
        this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    public javax.swing.JButton despliegue1;
    public javax.swing.JButton despliegue10;
    public javax.swing.JButton despliegue11;
    public javax.swing.JButton despliegue2;
    public javax.swing.JButton despliegue3;
    public javax.swing.JButton despliegue4;
    public javax.swing.JButton despliegue5;
    public javax.swing.JButton despliegue6;
    public javax.swing.JButton despliegue7;
    public javax.swing.JButton despliegue8;
    public javax.swing.JButton despliegue9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
