/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorBatalla;

/**
 *
 * @author Lucas
 */
public class Magias extends javax.swing.JPanel {
    
    ControladorBatalla controlador;

    /**
     * Creates new form Magias
     */
    public Magias(ControladorBatalla cb) {
        initComponents();
        this.controlador = cb;
        this.setSize(399, 401);
        lluviaTorrencial.setEnabled(false);
        lluviaTorrencial.setToolTipText("Las criaturas oponentes gastan dos movimientos en vez de uno por 3 turnos");
        hierbasVenenosas.setToolTipText("Selecciona 3 criaturas enemigas. Estas reciben 20% de su vida máxima de daño durante 3 turnos.");
        meteoritoDeFuego.setToolTipText("Selecciona un área de radio 5 cuadritos. Las criaturas oponentes que estén en esta área reciben "
                + "un daño de 30% de su vida máxima.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lluviaTorrencial = new javax.swing.JButton();
        hierbasVenenosas = new javax.swing.JButton();
        meteoritoDeFuego = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione la magia que desea invocar.");

        jLabel2.setText("Puede mantener el mouse sobre el botón para ver la descripción.");

        lluviaTorrencial.setText("Lluvia Torrencial");
        lluviaTorrencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lluviaTorrencialActionPerformed(evt);
            }
        });

        hierbasVenenosas.setText("Hierbas venenosas.");
        hierbasVenenosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hierbasVenenosasActionPerformed(evt);
            }
        });

        meteoritoDeFuego.setText("Meteorito de fuego");
        meteoritoDeFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meteoritoDeFuegoActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Coste: 10 de magia.");

        jLabel4.setText("Coste: 15 de magia.");

        jLabel5.setText("Coste: 20 de magia.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lluviaTorrencial, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))
                                    .addComponent(meteoritoDeFuego))
                                .addComponent(hierbasVenenosas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(lluviaTorrencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(hierbasVenenosas)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(meteoritoDeFuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lluviaTorrencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lluviaTorrencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lluviaTorrencialActionPerformed

    private void hierbasVenenosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hierbasVenenosasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hierbasVenenosasActionPerformed

    private void meteoritoDeFuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meteoritoDeFuegoActionPerformed

        this.controlador.setBoton(24);
    }//GEN-LAST:event_meteoritoDeFuegoActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
       this.setVisible(false);
       this.controlador.tablero.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton hierbasVenenosas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lluviaTorrencial;
    private javax.swing.JButton meteoritoDeFuego;
    // End of variables declaration//GEN-END:variables
}
